# 2. Numpy exercies
## a. Create a null vector of size 10 but the fifth value which is 1

In [9]:
import numpy as np
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

## b. Create a vector with values ranging from 10 to 49

In [2]:
import numpy as np
a = np.arange(10, 50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## c. Reverse a vector (first element becomes last)

In [16]:
import numpy as np
a = np.arange(0, 10)
a = np.flipud(a)
a

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## d. Create a 3x3 matrix with values ranging from 0 to 8

In [17]:
import numpy as np
A = np.arange(0, 9).reshape(3, 3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## e. Find indices of non-zero elements from [1,2,0,0,4,0]

In [23]:
import numpy as np
a = np.array([1, 2, 0, 0, 4, 0])
idx = np.where(a != 0)
idx

(array([0, 1, 4]),)

## f. Create a random vector of size 30 and find the mean value

In [31]:
import numpy as np
a = np.random.random(30)
a_mean = np.mean(a)
a_mean

np.float64(0.5044353546853385)

## g. Create a 2d array with 1 on the border and 0 inside

In [64]:
import numpy as np
n = 4
A = np.zeros(n**2).reshape(n, n)
A[[0,-1], :] = 1
A[:, [0,-1]] = 1
A

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

## h. Create a 8x8 matrix and fill it with a checkerboard pattern

In [100]:
import numpy as np
A = np.indices((8, 8)).sum(axis=0) % 2
A

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

## i. Create a checkerboard 8x8 matrix using the tile function

In [121]:
import numpy as np
np.tile([[0, 1],[1,0]], (4, 4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

## j. Given a 1D array, negate all elements which are between 3 and 8, in place

## k. Create a random vector of size 10 and sort it

## l. Consider two random array A and B, check if they are equal

## m. How to calculate the square of every number in an array in place (without creating temporaries)?

## n. How to get the diagonal of a dot product?

# 3. Speed optimization using Numpy
Revisit the `matmult.py` example from yesterday and improve its performance using Numpy.

In [24]:
# Program to multiply two matrices using nested loops
import random
import time

start = time.time()

N = 250

# NxN matrix
X = []
for i in range(N):
    X.append([random.randint(0,100) for r in range(N)])

# Nx(N+1) matrix
Y = []
for i in range(N):
    Y.append([random.randint(0,100) for r in range(N+1)])

# result is Nx(N+1)
result = []
for i in range(N):
    result.append([0] * (N+1))

# iterate through rows of X
for i in range(len(X)):
    # iterate through columns of Y
    for j in range(len(Y[0])):
        # iterate through rows of Y
        for k in range(len(Y)):
            result[i][j] += X[i][k] * Y[k][j]

end = time.time()

print("Execution time: {:.2f} s.".format(end - start))

#for r in result:
#    print(r)

Execution time: 1.58 s.


In [25]:
# Program to multiply two matrices using nested loops
import random
import time
import numpy as np

start = time.time()

N = 250

# NxN matrix
X = np.random.randint(0, 100, (N, N))
#print("X is size {:}".format(X.shape))

# Nx(N+1) matrix
Y = np.random.randint(0, 100, (N, N+1))
#print("Y is size {:}".format(Y.shape))

result = np.matmul(X, Y)
print("result is size {:}".format(result.shape))

end = time.time()

print("Execution time: {:.2f} s.".format(end - start))

#for r in result:
#    print(r)

result is size (250, 251)
Execution time: 0.02 s.
